# Generated by Django 5.0.7 on 2025-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
