# Generated by Django 5.0.7 on 2025-08-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0002_lote_finalizado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='quantidade_inicial',
        ),
    ]
