# Generated by Django 5.0.7 on 2025-08-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0003_remove_lote_quantidade_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacaoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FASE1', 'Fase 1'), ('FASE2', 'Fase 2'), ('FASE3', 'Fase 3'), ('INICIAL', 'Inicial')], max_length=10)),
                ('origem', models.CharField(max_length=120)),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade')),
                ('data', models.DateField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racoes', to='porktekapp.lote')),
            ],
        ),
    ]
