# Generated by Django 5.0.7 on 2025-08-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0004_racaoentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('peso_total', models.FloatField(help_text='Peso total (kg)')),
                ('peso_medio', models.FloatField(help_text='Peso médio (kg)')),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='porktekapp.lote')),
            ],
        ),
    ]
