# Generated by Django 5.0.7 on 2025-08-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0005_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saida',
            name='criado_em',
        ),
    ]
