# Generated by Django 5.0.7 on 2025-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0006_remove_saida_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='morte',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('ND', 'Não definido')], default='ND', max_length=2),
        ),
    ]
