# Generated by Django 5.0.7 on 2025-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0007_morte_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegada',
            name='peso_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
