# Generated by Django 5.0.7 on 2025-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porktekapp', '0008_chegada_peso_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegada',
            name='idade_media_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
